#define uintbig_p NAMESPACEBITS(uintbig_p)
#define uintbig_1 NAMESPACEBITS(uintbig_1)
#define uintbig_bit NAMESPACEBITS(uintbig_bit)
#define uintbig_set NAMESPACEBITS(uintbig_set)
#define uintbig_add NAMESPACEBITS(uintbig_add)
#define uintbig_sub NAMESPACEBITS(uintbig_sub)
#define uintbig_mul3_64 NAMESPACEBITS(uintbig_mul3_64)
#define uintbig_four_sqrt_p NAMESPACEBITS(uintbig_four_sqrt_p)
