#!/bin/sh

version=`cat packageversion`

rm -rf high-ctidh-$version
mkdir high-ctidh-$version

cp `git ls-files | grep -v '^package'` high-ctidh-$version
tar --owner=root --group=root --sort=name \
  -cf - high-ctidh-$version \
| gzip -9 > high-ctidh-$version.tar.gz
rm -rf high-ctidh-$version
