// DO NOT EDIT! generated by ./autogen

#ifndef primes_h
#define primes_h

#include "../common/namespace.h"


#define primes NAMESPACEBITS(primes)
#define primes_dac NAMESPACEBITS(primes_dac)
#define primes_daclen NAMESPACEBITS(primes_daclen)
#define batch_start NAMESPACEBITS(batch_start)
#define batch_stop NAMESPACEBITS(batch_stop)
#define batch_keybounds_start NAMESPACEBITS(batch_keybounds_start)
#define batch_keybounds_stop NAMESPACEBITS(batch_keybounds_stop)
#define batch_numkeys NAMESPACEBITS(batch_numkeys)
#define batch_maxdac NAMESPACEBITS(batch_maxdac)
#define batch_maxdac NAMESPACEBITS(batch_maxdac)
#define batch_maxdac NAMESPACEBITS(batch_maxdac)



 #if defined  P2047m1l226
#define primes_num 226
#define two_cofactor 64
#define primes_batches 19
#define WOMBATKEYS 73
#define NUMBER_OF_WORDS 32
#define UPPER_BOUND 1044  // Bits of 4 * sqrt( [p + 1] / [2^e] )
#define ELLIGATOR_SEED 2 
#else
#error NO PRIME#endif

extern const long long primes[primes_num];
extern const long long primes_dac[primes_num];
extern const long long primes_daclen[primes_num];
extern const long long batch_start[primes_batches];
extern const long long batch_stop[primes_batches];
extern const long long batch_keybounds_start[primes_batches+1];
extern const long long batch_keybounds_stop[primes_batches];
extern const long long batch_numkeys[primes_batches];
extern const long long batch_maxdac[primes_batches];

#endif
