/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_2047m4l207_uintbig_1
secsidh_internal_2047m4l207_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_2047m4l207_uintbig_1_ctidh
secsidh_internal_2047m4l207_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_2047m4l207_uintbig_p
secsidh_internal_2047m4l207_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0x5d2792fcea42b018, 0xb6725ecd7ca11504, 0x86b544f84145592b, 0x81d3c1adc7977dae
    .quad 0x33b715b3006c130f, 0x4fa2428dee7a6adb, 0x0b3ccc301164bf3d, 0xca424f13b2245791
    .quad 0x7439f13a079a8e3d, 0xe16d5dababf5eb8e, 0x99e91c9c1a7ba3ef, 0x4d2941916adc762a
    .quad 0xab650062b36ab380, 0xfbdd2704e6b89357, 0xfcc0206c307af401, 0xa30e106b711c3db8
    .quad 0x9083164f44c3d435, 0x094f0b805d59656b, 0x939f23a53617c370, 0x9be8e968486eb7e8
    .quad 0x1609c664b7e30d83, 0x104b0031b0d5bda4, 0x8443ae7f5307c867, 0x484a1a0ed2abee7e
    .quad 0xf72c45b079e435d4, 0x9875bd5d246f2d35, 0xde35711dac11d84c, 0x6c76ac40b24e2eda

.global secsidh_internal_2047m4l207_uintbig_four_sqrt_p
secsidh_internal_2047m4l207_uintbig_four_sqrt_p:
    .quad 0x06826ead273cd099, 0x022db915544badb0, 0xf84fdfda43f87174, 0xe678a5a39d3c9916
    .quad 0xb4a3a6ff93a5f034, 0x0c14df8632147eb6, 0x2a436ca68e9605e8, 0xf2fc6fc32ee02801
    .quad 0xaec0eca3e3fa7987, 0xb2d46d198bc953d9, 0xb5b1b71ad379391f, 0xf9e337e184f0409d
    .quad 0x4551445c3af080cb, 0x7d9c1ee8a436258d, 0x9f31e555a6b3c0d3, 0x9a888c885d91b255
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_2047m4l207_uintbig_set
secsidh_internal_2047m4l207_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 31
    rep stosq
    ret


.global secsidh_internal_2047m4l207_uintbig_bit
secsidh_internal_2047m4l207_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_2047m4l207_uintbig_add
secsidh_internal_2047m4l207_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_2047m4l207_uintbig_sub
secsidh_internal_2047m4l207_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_2047m4l207_uintbig_mul3_64
secsidh_internal_2047m4l207_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    ret
