// DO NOT EDIT! generated by ./autogen

#ifndef primes_h
#define primes_h

#include "../common/namespace.h"
#include <inttypes.h>

#if defined  P2047m1l226
#define primes_num 226
#define two_cofactor 64
#define primes_batches 19
#define WOMBATKEYS 73
#define NUMBER_OF_WORDS 32
#define UPPER_BOUND 1044  // Bits of 4 * sqrt( [p + 1] / [2^e] )
#define ELLIGATOR_SEED 2 

#elif defined  P2047m4l205
#define primes_num 207
#define two_cofactor 287
#define primes_batches 13
#define WOMBATKEYS 68
#define NUMBER_OF_WORDS 32
#define UPPER_BOUND 1044  // Bits of 4 * sqrt( [p + 1] / [2^e] )
#define ELLIGATOR_SEED 15

#elif defined  P2047m6l194
#define primes_num 196
#define two_cofactor 391
#define primes_batches 12
#define WOMBATKEYS 69
#define NUMBER_OF_WORDS 32
#define UPPER_BOUND 1044  // Bits of 4 * sqrt( [p + 1] / [2^e] )
#define ELLIGATOR_SEED 4

#elif defined  P2047m7l188
#define primes_num 190
#define two_cofactor 450
#define primes_batches 10
#define WOMBATKEYS 70
#define NUMBER_OF_WORDS 32
#define UPPER_BOUND 1044  // Bits of 4 * sqrt( [p + 1] / [2^e] )
#define ELLIGATOR_SEED 7
#else

#error BITS must be 2048
#endif

#define primes NS(primes)
#define primes_dac NS(primes_dac)
#define primes_daclen NS(primes_daclen)

#define batch_start NS(batch_start)
#define batch_stop NS(batch_stop)
#define batch_keybounds_start NS(batch_keybounds_start)
#define batch_keybounds_stop NS(batch_keybounds_stop)
#define batch_numkeys NS(batch_numkeys)
#define batch_maxdac NS(batch_maxdac)

extern const int64_t primes[primes_num];
extern const int64_t primes_dac[primes_num];
extern const int64_t primes_daclen[primes_num];
extern const int64_t batch_start[primes_batches];
extern const int64_t batch_stop[primes_batches];
extern const int64_t batch_keybounds_start[primes_batches+1];
extern const int64_t batch_keybounds_stop[primes_batches];
extern const int64_t batch_numkeys[primes_batches];
extern const int64_t batch_maxdac[primes_batches];
extern const int8_t  strategy[WOMBATKEYS];

#endif
