/* DO NOT EDIT! generated by ./autogen */

.intel_syntax noprefix

#include "uintbig_namespace.h"

.section .rodata

.global secsidh_internal_2047m6l194_uintbig_1
secsidh_internal_2047m6l194_uintbig_1:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_2047m6l194_uintbig_1_ctidh
secsidh_internal_2047m6l194_uintbig_1_ctidh:
    .quad 1, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.global secsidh_internal_2047m6l194_uintbig_p
secsidh_internal_2047m6l194_uintbig_p:
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff, 0xffffffffffffffff
    .quad 0xffffffffffffffff, 0xffffffffffffffff, 0x1b908af37d000377, 0xf182321720af02f7
    .quad 0x05f9a0f21145a4ac, 0x8e026ed9f368069d, 0x917384af300d371b, 0xcbdfa2daa8e74975
    .quad 0x3ef38bf8f4cc53bd, 0xd4e4460a7b4238bb, 0x88b5145f0b10af23, 0xe4f78c3436cb7c55
    .quad 0x10c05b78802d2051, 0x02f1b1714e5b4fb4, 0x75de67ceb9df3e85, 0x3971e6dee1971014
    .quad 0xb68d129db2363015, 0x5ca39cb55635cfb2, 0x4331b79976871e2d, 0x15ebb5442f84dd73
    .quad 0xe7258b20d8e42076, 0x7388d3f24a1bd018, 0xbe64585bf42917ac, 0xb72a1c4b011b2a64
    .quad 0x3d437c0cc96147c8, 0xdd293ec0a068274e, 0x0088ef521fb9bb94, 0x44865706f14d9318

.global secsidh_internal_2047m6l194_uintbig_four_sqrt_p
secsidh_internal_2047m6l194_uintbig_four_sqrt_p:
    .quad 0xb2eea7114cc32f1b, 0xe09f6108a58c8947, 0x29d63c9240c40abc, 0x360b1d30e472ca01
    .quad 0x8f74a59c9078b8f1, 0x545ba45b69aaba31, 0x36b7cd256c6dcb72, 0x513b10823feaa3c8
    .quad 0x67f4b131f93938ae, 0x4d30e9728b3840dc, 0x69971830625cce43, 0x07c583ae03f8c22e
    .quad 0xf821d298f5e3b680, 0x67d634a58d3a769b, 0x399a857caeced861, 0x11ca3d22f97ade97
    .quad 2, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0
    .quad 0, 0, 0, 0

.section .text

.global secsidh_internal_2047m6l194_uintbig_set
secsidh_internal_2047m6l194_uintbig_set:
    cld
    mov rax, rsi
    stosq
    xor rax, rax
    mov rcx, 31
    rep stosq
    ret


.global secsidh_internal_2047m6l194_uintbig_bit
secsidh_internal_2047m6l194_uintbig_bit:
    mov rcx, rsi
    and rcx, 0x3f
    shr rsi, 6
    mov rax, [rdi + 8*rsi]
    shr rax, cl
    and rax, 1
    ret


.global secsidh_internal_2047m6l194_uintbig_add
secsidh_internal_2047m6l194_uintbig_add:
    mov rax, [rsi +  0]
    add rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        adc rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret

.global secsidh_internal_2047m6l194_uintbig_sub
secsidh_internal_2047m6l194_uintbig_sub:
    mov rax, [rsi +  0]
    sub rax, [rdx +  0]
    mov [rdi +  0], rax
    .set k, 1
    .rept 31
        mov rax, [rsi + 8*k]
        sbb rax, [rdx + 8*k]
        mov [rdi + 8*k], rax
        .set k, k+1
    .endr
    setc al
    movzx rax, al
    ret


.global secsidh_internal_2047m6l194_uintbig_mul3_64
secsidh_internal_2047m6l194_uintbig_mul3_64:

    mulx r10, rax, [rsi +  0]
    mov [rdi +  0], rax

    mulx r11, rax, [rsi + 8]
    add  rax, r10
    mov [rdi + 8], rax

    mulx r10, rax, [rsi + 16]
    adcx rax, r11
    mov [rdi + 16], rax

    mulx r11, rax, [rsi + 24]
    adcx rax, r10
    mov [rdi + 24], rax

    mulx r10, rax, [rsi + 32]
    adcx rax, r11
    mov [rdi + 32], rax

    mulx r11, rax, [rsi + 40]
    adcx rax, r10
    mov [rdi + 40], rax

    mulx r10, rax, [rsi + 48]
    adcx rax, r11
    mov [rdi + 48], rax

    mulx r11, rax, [rsi + 56]
    adcx rax, r10
    mov [rdi + 56], rax

    mulx r10, rax, [rsi + 64]
    adcx rax, r11
    mov [rdi + 64], rax

    mulx r11, rax, [rsi + 72]
    adcx rax, r10
    mov [rdi + 72], rax

    mulx r10, rax, [rsi + 80]
    adcx rax, r11
    mov [rdi + 80], rax

    mulx r11, rax, [rsi + 88]
    adcx rax, r10
    mov [rdi + 88], rax

    mulx r10, rax, [rsi + 96]
    adcx rax, r11
    mov [rdi + 96], rax

    mulx r11, rax, [rsi + 104]
    adcx rax, r10
    mov [rdi + 104], rax

    mulx r10, rax, [rsi + 112]
    adcx rax, r11
    mov [rdi + 112], rax

    mulx r11, rax, [rsi + 120]
    adcx rax, r10
    mov [rdi + 120], rax

    mulx r10, rax, [rsi + 128]
    adcx rax, r11
    mov [rdi + 128], rax

    mulx r11, rax, [rsi + 136]
    adcx rax, r10
    mov [rdi + 136], rax

    mulx r10, rax, [rsi + 144]
    adcx rax, r11
    mov [rdi + 144], rax

    mulx r11, rax, [rsi + 152]
    adcx rax, r10
    mov [rdi + 152], rax

    mulx r10, rax, [rsi + 160]
    adcx rax, r11
    mov [rdi + 160], rax

    mulx r11, rax, [rsi + 168]
    adcx rax, r10
    mov [rdi + 168], rax

    mulx r10, rax, [rsi + 176]
    adcx rax, r11
    mov [rdi + 176], rax

    mulx r11, rax, [rsi + 184]
    adcx rax, r10
    mov [rdi + 184], rax

    mulx r10, rax, [rsi + 192]
    adcx rax, r11
    mov [rdi + 192], rax

    mulx r11, rax, [rsi + 200]
    adcx rax, r10
    mov [rdi + 200], rax

    mulx r10, rax, [rsi + 208]
    adcx rax, r11
    mov [rdi + 208], rax

    mulx r11, rax, [rsi + 216]
    adcx rax, r10
    mov [rdi + 216], rax

    mulx r10, rax, [rsi + 224]
    adcx rax, r11
    mov [rdi + 224], rax

    mulx r11, rax, [rsi + 232]
    adcx rax, r10
    mov [rdi + 232], rax

    mulx r10, rax, [rsi + 240]
    adcx rax, r11
    mov [rdi + 240], rax

    mulx r11, rax, [rsi + 248]
    adcx rax, r10
    mov [rdi + 248], rax

    ret
